/**
 * Reusable dev script for Electron + Angular framework projects.
 * Builds framework, watches TypeScript, and restarts Electron on changes.
 *
 * Usage from consumer's package.json:
 *   "electron:watch": "node node_modules/@bibi2400/electron-angular-framework/dist/cli/scripts/electron-dev.js"
 * Or via the scripts/electron-dev.js wrapper generated by eaf create.
 */

const { spawn, execSync } = require('child_process');
const path = require('path');

const isWindows = process.platform === 'win32';
let electronProcess = null;
let isShuttingDown = false;
let outputBuffer = '';

function killProcessTree(childProcess) {
  if (!childProcess || !childProcess.pid) return;
  try {
    if (isWindows) {
      // /F = force, /T = kill entire process tree
      execSync(`taskkill /F /T /PID ${childProcess.pid}`, { stdio: 'ignore', timeout: 5000 });
    } else {
      // Kill process group on Unix
      process.kill(-childProcess.pid, 'SIGKILL');
    }
  } catch {
    // Process may have already exited, try direct kill as fallback
    try { childProcess.kill('SIGKILL'); } catch {}
  }
}

// Build framework first (if present)
const frameworkTsconfig = path.join(process.cwd(), 'packages', 'framework', 'tsconfig.json');
const fs = require('fs');
if (fs.existsSync(frameworkTsconfig)) {
  console.log('[dev] Building framework...');
  try {
    let tscBinForFramework;
    try {
      tscBinForFramework = require.resolve('typescript/bin/tsc');
    } catch {
      tscBinForFramework = path.join(process.cwd(), 'node_modules', 'typescript', 'bin', 'tsc');
    }
    execSync(`"${process.execPath}" "${tscBinForFramework}" -p "${frameworkTsconfig}"`, { stdio: 'inherit' });
    console.log('[dev] Framework built successfully');
  } catch (error) {
    console.error('[dev] Framework build failed:', error.message);
    process.exit(1);
  }
}

// Resolve tsc binary to spawn node directly — avoids cmd.exe shell wrapper on Windows,
// which prevents orphan processes when Ctrl+C kills the shell but not its children.
let tscBin;
try {
  tscBin = require.resolve('typescript/bin/tsc');
} catch {
  tscBin = path.join(process.cwd(), 'node_modules', 'typescript', 'bin', 'tsc');
}

const tscProcess = spawn(process.execPath, [tscBin, '-p', 'electron/tsconfig.json', '--watch', '--preserveWatchOutput'], {
  stdio: ['inherit', 'pipe', 'inherit'],
  detached: !isWindows, // Unix: create process group so we can kill the whole tree
});

console.log('[dev] TypeScript watch started');

tscProcess.stdout.on('data', (data) => {
  const output = data.toString();
  process.stdout.write(output);
  outputBuffer += output;

  if (outputBuffer.includes('Found 0 errors')) {
    outputBuffer = '';
    if (!isShuttingDown) {
      restartElectron();
    }
  }

  if (output.includes('File change detected') || output.includes('Starting compilation')) {
    outputBuffer = '';
  }
});

function restartElectron() {
  if (electronProcess) {
    console.log('[dev] Stopping Electron for restart...');
    const oldProcess = electronProcess;
    electronProcess = null;
    killProcessTree(oldProcess);
    setTimeout(() => startElectron(), isWindows ? 1000 : 300);
  } else {
    startElectron();
  }
}

function startElectron() {
  if (isShuttingDown) return;
  console.log('[dev] Starting Electron...');

  const electronPath = require('electron');
  const extraArgs = process.argv.slice(2);
  electronProcess = spawn(electronPath, ['--inspect=9229', '.', '--serve', ...extraArgs], {
    stdio: ['inherit', 'pipe', 'pipe'],
    env: { ...process.env },
  });

  // Pipe Electron output through Node so Chromium can't alter the console code page
  electronProcess.stdout.on('data', (d) => process.stdout.write(d));
  electronProcess.stderr.on('data', (d) => process.stderr.write(d));

  electronProcess.on('close', (code) => {
    console.log(`[dev] Electron exited with code ${code}`);
    if (electronProcess !== null) {
      electronProcess = null;
      if (code === 0 && !isShuttingDown) {
        console.log('[dev] Electron closed normally, shutting down dev environment...');
        shutdown();
      }
    }
  });

  electronProcess.on('error', (err) => {
    console.error('[dev] Failed to start Electron:', err);
  });
}

function shutdown() {
  if (isShuttingDown) return;
  isShuttingDown = true;
  console.log('[dev] Shutting down...');

  killProcessTree(electronProcess);
  killProcessTree(tscProcess);

  // Exit immediately — the synchronous kills above have already fired.
  // Delaying (even with setTimeout) risks the process hanging because
  // capturing SIGINT disables Node's default exit, and orphaned pipe refs
  // can keep the event loop alive indefinitely on Windows.
  process.exit(0);
}

// Handle Ctrl+C — on Windows SIGINT is delivered to the entire console group,
// so child processes may already be dying when we get here.
process.on('SIGINT', () => {
  shutdown();
});
process.on('SIGTERM', () => {
  shutdown();
});

tscProcess.on('close', (code) => {
  console.log(`[dev] TypeScript watch exited with code ${code}`);
  if (!isShuttingDown) {
    shutdown();
  }
});
